import "./globals.css";
import { ClerkProvider, SignIn, auth } from "@clerk/nextjs";
import { sql } from "@vercel/postgres";
import CreateAccount from "./components/CreateAccount";
import NavBar from "./components/NavBar";
import { Suspense } from "react";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const { userId } = auth();

    const { rowCount } =
        await sql`SELECT * FROM fb_users WHERE auth_id=${userId}`;

    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    <Suspense
                        fallback={
                            <div className="bg-gray-400 animate-pulse h-[10vh] w-full"></div>
                        }
                    >
                        <NavBar />
                    </Suspense>
                    {rowCount !== 0 && children}
                    {/* {!userId && <SignIn />} */}
                    {userId && rowCount === 0 && <CreateAccount />}
                </body>
            </html>
        </ClerkProvider>
    );
}
